version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

