spring:
  application:
    name: order-service
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order_db}
    user: ${DB_USER:postgres}
    password: ${DB_PASS:postgres_pass}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres_pass}
    driver-class-name: org.postgresql.Driver
    name: order_db
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:order_db}
server:
  port: 8081
logging:
  log4j2:
    config:
      override: src/main/resources/log4j2.xml

